config/routes.rb
Kassi::Application.routes.draw do
  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  match "/robots.txt" => RobotsGenerator

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  match "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get '/webhooks/braintree' => 'braintree_webhooks#challenge'
  post '/webhooks/braintree' => 'braintree_webhooks#hooks'
  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook

  post '/bounces' => 'amazon_bounces#notification'

  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  match "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :admin do
    match '' => "communities#getting_started"
  end

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    get "/check_email_availability" => "marketplaces#check_email_availability"
  end

  REMOVED_LOCALES = Rails.application.config.REMOVED_LOCALES.to_a

  locale_matcher = Regexp.new(Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(REMOVED_LOCALES).join("|"))

  match '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  match '/' => 'homepage#index', as: :homepage_without_locale
  root :to => 'homepage#index'

  match '/500' => 'errors#server_error'
  match '/404' => 'errors#not_found', :as => :error_not_found
  match '/410' => 'errors#gone', as: :error_gone
  match '/community_not_found' => 'errors#community_not_found', as: :community_not_found

  resources :communities, only: [:new, :create]

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    match '/mercury_update' => "mercury_update#update", :as => :mercury_update, :method => :put

    match "/transactions/op_status/:process_token" => "transactions#op_status", :as => :transaction_op_status

    match "/transactions/new" => "transactions#new", as: :new_transaction

    match "/listings/:listing_id/preauthorize" => "preauthorize_transactions#preauthorize", :as => :preauthorize_payment
    match "/listings/:listing_id/preauthorized" => "preauthorize_transactions#preauthorized", :as => :preauthorized_payment
    match "/listings/:listing_id/book" => "preauthorize_transactions#book", :as => :book
    match "/listings/:listing_id/booked" => "preauthorize_transactions#booked", :as => :booked
    match "/listings/:listing_id/initiate" => "preauthorize_transactions#initiate", :as => :initiate_order
    match "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    match "/listings/:listing_id/post_pay" => "post_pay_transactions#new", :as => :post_pay_listing
    match "/listings/:listing_id/create_transaction" => "post_pay_transactions#create", :as => :create_transaction, :method => :post

    match "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    match "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    match "/listings/new/:type/:category" => "listings#new", :as => :new_request_category
    match "/listings/new/:type" => "listings#new", :as => :new_request
    match "/logout" => "sessions#destroy", :as => :logout, :method => :delete
    match "/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
    match "/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
    match "/login" => "sessions#new", :as => :login
    match "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    match "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    match '/:person_id/settings/payments/braintree/new' => 'braintree_accounts#new', :as => :new_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/show' => 'braintree_accounts#show', :as => :show_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/create' => 'braintree_accounts#create', :as => :create_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/add_braintree_customer' => 'braintree_accounts#add_braintree_customer', :as => :add_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/update_braintree_customer' => 'braintree_accounts#update_braintree_customer', :as => :update_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/create_braintree_customer' => 'braintree_accounts#create_braintree_customer', :as => :create_braintree_settings_customer
    match '/:person_id/settings/payments/paypal_account/new' => 'paypal_accounts#new', :as => :new_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/show' => 'paypal_accounts#show', :as => :show_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/create' => 'paypal_accounts#create', :as => :create_paypal_account_settings_payment
    get '/auth_stripe' =>"transactions#auth_stripe"
    post "/listing_calculation" => "listings#listing_calculation"

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do

      resources :communities do
        member do
          get :getting_started, to: 'communities#getting_started'
          get :edit_details, to: 'community_customizations#edit_details'
          put :update_details, to: 'community_customizations#update_details'
          get :edit_look_and_feel
          put :edit_look_and_feel, to: 'communities#update_look_and_feel'
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :settings
          get :payment_gateways
          put :payment_gateways, to: 'communities#update_payment_gateway'
          post :payment_gateways, to: 'communities#create_payment_gateway'
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          get :menu_links
          put :menu_links, to: 'communities#update_menu_links'
          put :update_settings
          delete :delete_marketplace
        end
        resources :transactions, controller: :community_transactions, only: :index
        resources :emails
        resources :community_memberships do
          member do
            put :ban
            put :verify_user
          end
          collection do
            post :promote_admin
            post :posting_allowed
          end
        end
        resource :paypal_preferences, only: :index do
          member do
            get :index
            post :preferences_update
            get :account_create
            get :permissions_verified
          end
        end
      end
      resources :custom_fields do
        collection do
          get :add_option
          get :edit_price
          get :edit_location
          post :order
          put :update_price
          put :update_location
        end
      end
      resources :categories do
        member do
          get :remove
          delete :destroy_and_move
        end
        collection do
          post :order
        end
      end
      resources :listing_shapes do
        collection do
          post :order
        end
        member do
          get :close_listings
        end
      end
    end

    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :community_memberships, :as => :tribe_memberships do
      collection do
        get :access_denied
      end
    end
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :new_form_content
        get :edit_form_content
        get :more_listings
        get :browse
        get :locations_json
        get :verification_required
      end
      resources :comments
      resources :listing_images do
        collection do
          post :add_from_file
          put :add_from_url
        end
      end
    end

    resources :listing_images do
      member do
        get :image_status
      end
      collection do
        post :add_from_file
        put :add_from_url
      end
    end

    resources :infos do
      collection do
        get :about
        get :terms
        get :privacy
        get :news
        get :trust_and_safety
        get :faq
        get :claim
        get :contact
      end
    end
    resource :terms do
      member do
        post :accept
      end
    end
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end
    resources :consent
    resource :sms do
      get :message_arrived
    end

    devise_for :people, :controllers => { :confirmations => "confirmations", :registrations => "people", :omniauth_callbacks => "sessions"}, :path_names => { :sign_in => 'login'}
    devise_scope :person do
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      match "/people/password/edit" => "devise/passwords#edit"
      post "/people/password" => "devise/passwords#create"
      put "/people/password" => "devise/passwords#update"

app/models/custom_fields/checkbox_field.rb
# == Schema Information
#
# Table name: custom_fields
#
#  id             :integer          not null, primary key
#  type           :string(255)
#  sort_priority  :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  community_id   :integer
#  required       :boolean          default(TRUE)
#  min            :float
#  max            :float
#  allow_decimals :boolean          default(FALSE)
#
# Indexes
#
#  index_custom_fields_on_community_id  (community_id)
#

class CheckboxField < OptionField
  validates_length_of :options, :minimum => 1

  def with_type(&block)
    block.call(:checkbox)
  end

  def can_filter?
    true
  end
end

app/models/custom_fields/date_field.rb
# == Schema Information
#
# Table name: custom_fields
#
#  id             :integer          not null, primary key
#  type           :string(255)
#  sort_priority  :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  community_id   :integer
#  required       :boolean          default(TRUE)
#  min            :float
#  max            :float
#  allow_decimals :boolean          default(FALSE)
#
# Indexes
#
#  index_custom_fields_on_community_id  (community_id)
#

class DateField < CustomField
  def with_type(&block)
    block.call(:date_field)
  end
end

app/controllers/admin/custom_fields_controller.rb
class Admin::CustomFieldsController < ApplicationController

  before_filter :ensure_is_admin
  before_filter :field_type_is_valid, :only => [:new, :create]

  def index
    @selected_left_navi_link = "listing_fields"
    @community = @current_community
    @custom_fields = @current_community.custom_fields

    shapes = listings_api.shapes.get(community_id: @community.id).data
    price_in_use = shapes.any? { |s| s[:price_enabled] }

    render locals: { show_price_filter: price_in_use }
  end

  def new
    @selected_left_navi_link = "listing_fields"
    @community = @current_community
    @custom_field = params[:field_type].constantize.new #before filter checks valid field types and prevents code injection

    if params[:field_type] == "CheckboxField"
      @min_option_count = 1
      @custom_field.options = [CustomFieldOption.new(sort_priority: 1)]
    else
      @min_option_count = 2
      @custom_field.options = [CustomFieldOption.new(sort_priority: 1), CustomFieldOption.new(sort_priority: 2)]
    end
  end

  def create
    @selected_left_navi_link = "listing_fields"
    @community = @current_community

    # Hack for comma/dot issue. Consider creating an app-wide comma/dot handling mechanism
    params[:custom_field][:min] = ParamsService.parse_float(params[:custom_field][:min]) if params[:custom_field][:min].present?
    params[:custom_field][:max] = ParamsService.parse_float(params[:custom_field][:max]) if params[:custom_field][:max].present?

    @custom_field = params[:field_type].constantize.new(params[:custom_field]) #before filter checks valid field types and prevents code injection
    @custom_field.community = @current_community

    success = if valid_categories?(@current_community, params[:custom_field][:category_attributes])
      @custom_field.save
    end

    if success
      redirect_to admin_custom_fields_path
    else
      flash[:error] = "Listing field saving failed"
      render :new
    end
  end

  def edit
    @selected_tribe_navi_tab = "admin"
    @selected_left_navi_link = "listing_fields"
    @community = @current_community

    if params[:field_type] == "CheckboxField"
      @min_option_count = 1
    else
      @min_option_count = 2
    end

    @custom_field = CustomField.find(params[:id])
  end

  def update
    @custom_field = CustomField.find(params[:id])

    # Hack for comma/dot issue. Consider creating an app-wide comma/dot handling mechanism
    params[:custom_field][:min] = ParamsService.parse_float(params[:custom_field][:min]) if params[:custom_field][:min].present?
    params[:custom_field][:max] = ParamsService.parse_float(params[:custom_field][:max]) if params[:custom_field][:max].present?

    @custom_field.update_attributes(params[:custom_field])

    redirect_to admin_custom_fields_path
  end

  def edit_price
    @selected_tribe_navi_tab = "admin"
    @selected_left_navi_link = "listing_fields"
    @community = @current_community
  end

  def edit_location
    @selected_tribe_navi_tab = "admin"
    @selected_left_navi_link = "listing_fields"
    @community = @current_community
  end

  def update_price
    # To cents
    params[:community][:price_filter_min] = MoneyUtil.parse_str_to_money(params[:community][:price_filter_min], @current_community.default_currency).cents if params[:community][:price_filter_min]
    params[:community][:price_filter_max] = MoneyUtil.parse_str_to_money(params[:community][:price_filter_max], @current_community.default_currency).cents if params[:community][:price_filter_max]

    success = @current_community.update_attributes(params[:community])

    if success
      redirect_to admin_custom_fields_path
    else
      flash[:error] = "Price field editing failed"
      render :action => :edit_price
    end
  end

  def update_location
    success = @current_community.update_attributes(params[:community])

    if success
      redirect_to admin_custom_fields_path
    else
      flash[:error] = "Location field editing failed"
      render :action => :edit_location
    end
  end

  def destroy
    @custom_field = CustomField.find(params[:id])

    success = if custom_field_belongs_to_community?(@custom_field, @current_community)
      @custom_field.destroy
    end

    flash[:error] = "Field doesn't belong to current community" unless success
    redirect_to admin_custom_fields_path
  end

  def order
    sort_priorities = params[:order].each_with_index.map do |custom_field_id, index|
      [custom_field_id, index]
    end.inject({}) do |hash, ids|
      custom_field_id, sort_priority = ids
      hash.merge(custom_field_id.to_i => sort_priority)
    end

    @current_community.custom_fields.each do |custom_field|
      custom_field.update_attributes(:sort_priority => sort_priorities[custom_field.id])
    end

    render nothing: true, status: 200
  end

  private

  # Return `true` if all the category id's belong to `community`
  def valid_categories?(community, category_attributes)
    is_community_category = category_attributes.map do |category|
      community.categories.any? { |community_category| community_category.id == category[:category_id].to_i }
    end

    is_community_category.all?
  end

  def custom_field_belongs_to_community?(custom_field, community)
    community.custom_fields.include?(custom_field)
  end

  private

  def field_type_is_valid
    redirect_to admin_custom_fields_path unless CustomField::VALID_TYPES.include?(params[:field_type])
  end

  def listings_api
    ListingService::API::Api
  end

end

app/helpers/custom_fields_helper.rb
module CustomFieldsHelper

  def field_type_translation(type)
    tranlation_map = {
      "DropdownField" => "admin.custom_fields.field_types.dropdown",
      "TextField" => "admin.custom_fields.field_types.text",
      "NumericField" => "admin.custom_fields.field_types.number",
      "CheckboxField" => "admin.custom_fields.field_types.checkbox_group",
      "DateField" => "admin.custom_fields.field_types.date"
    }

    t(tranlation_map[type])
  end

  def custom_field_dropdown_options(options)
    options.collect { |option| [field_type_translation(option), option] }.insert(0, [t("admin.custom_fields.index.select_one"), nil])
  end

end

app/views/admin/custom_fields/_listed_custom_field.haml
.row.custom-field-list-row{:data => {:"field-id" => custom_field.id}}
  .col-5
    %span.custom-fields-mobile-list-title.hidden-tablet
      = t("admin.custom_fields.index.field_title")
    = custom_field.name(I18n.locale)
  .col-5.custom-field-title
    %span.custom-fields-mobile-list-title.hidden-tablet
      = t("admin.custom_fields.index.field_type")
    %div
      = field_type_translation(custom_field.type)
    %div.custom-fields-details
      - custom_field.with(:dropdown) do
        = custom_field.options.sort.collect { |option| option.title(I18n.locale) }.join(", ")
      - custom_field.with(:checkbox) do
        = custom_field.options.sort.collect { |option| option.title(I18n.locale) }.join(", ")
      - custom_field.with(:numeric) do
        = "#{custom_field.display_min} &ndash; #{custom_field.display_max}".html_safe
  .col-2
    = link_to edit_admin_custom_field_path(custom_field), :class => "custom-fields-action-edit", :id => "edit_custom_field_#{custom_field.id}" do
      = icon_tag("edit", ["icon-fix"])
    = link_to admin_custom_field_path(custom_field), :method => :delete, :class => "custom-fields-action-remove", :confirm => t("admin.custom_fields.index.remove_field_confirmation", :field_name => custom_field.name(I18n.locale)) do
      = icon_tag("cross", ["icon-fix"])
    = link_to '#', :class => "custom-fields-action-up admin-sort-button", :tabindex => "-1" do
      = icon_tag("directup", ["icon-fix"])
    = link_to '#', :class => "custom-fields-action-down admin-sort-button", :tabindex => "-1" do
      = icon_tag("directdown", ["icon-fix"])

app/views/admin/custom_fields/_new_option.haml
.custom-field-option-container{:data => {:"field-id" => "#{option_id}"}}
  .custom-field-option-locales
    .row
      - show_locales = available_locales.size > 1
      .col-8{:class => show_locales ? "" : "custom-field-column-without-bottom-margin"}
        = fields_for "custom_field[option_attributes][#{option_id}][]", option do |option_form|
          - input_col_size = show_locales ? "9" : "12"
          - available_locales.each do |locale_name, locale_value|
            .row.custom-field-option-locale-row
              - if show_locales
                .col-3.custom-field-option-locale-column
                  = label_tag "custom_field[option_attributes][#{option_id}][title_attributes][#{locale_value}]", locale_name + ": ", :class => "custom-field-option-with-multiple-locales-label"
              .custom-field-option-locale-column{:class => "col-#{input_col_size}"}
                = text_field_tag "custom_field[option_attributes][#{option_id}][title_attributes][#{locale_value}]", option.title(locale_value), :class => "required", :value => option.title(locale_value), :id => "custom_field[option_attributes][#{option_id}][title_attributes][#{locale_value}]"
          = hidden_field_tag "custom_field[option_attributes][#{option_id}][sort_priority]", sort_priority, :class => "custom-field-hidden-sort-priority"
      .col-4.custom-field-actions
        - link_class = "custom-field-option-#{(show_locales ? "with" : "without")}-locale-remove"

        = link_to "#", :class => "custom-field-option-remove #{link_class}", :tabindex => "-1", :id => "custom-field-option-remove-#{option_id}" do
          = icon_tag("cross", ["icon-fix"])
        = link_to '#', :class => "custom-fields-action-up admin-sort-button", :tabindex => "-1" do
          = icon_tag("directup", ["icon-fix"])
        = link_to '#', :class => "custom-fields-action-down admin-sort-button", :tabindex => "-1" do
          = icon_tag("directdown", ["icon-fix"])

app/views/admin/custom_fields/edit.haml
- content_for :javascript do
  initialize_admin_listing_field_form_view("#{I18n.locale}", "#edit_custom_field", #{@custom_field.options.size}, #{@min_option_count});
  ST.customFieldOptionOrder = ST.createCustomFieldOptionOrder(".custom-field-option-container");

- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t("admin.custom_fields.edit.edit_listing_field", :field_name => @custom_field.name(I18n.locale))

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section
  = form_for @custom_field, :as => :custom_field, :url => admin_custom_field_path(@custom_field), :method => :put do |form|

    = render :partial => "admin/custom_fields/form/field_name", :locals => { :form => form }

    = render :partial => "admin/custom_fields/form/field_required", :locals => { :form => form, :custom_field => @custom_field }

    - @custom_field.with(:numeric) do
      = render :partial => "admin/custom_fields/form/field_min_max", :locals => { :form => form, :min => @custom_field.display_min, :max => @custom_field.display_max }

    = render :partial => "admin/custom_fields/form/field_categories", :locals => { :form => form }

    - @custom_field.with(:dropdown) do
      = render :partial => "admin/custom_fields/form/field_options", :locals => { :form => form }

    - @custom_field.with(:checkbox) do
      = render :partial => "admin/custom_fields/form/field_options", :locals => { :form => form }

    = render :partial => "admin/custom_fields/form/buttons", :locals => { :form => form }

app/views/admin/custom_fields/edit_location.haml
- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t(".edit_location_field")

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section
  = form_for @community, :as => :community, :url => update_location_admin_custom_fields_path, :method => :put do |form|

    .row
      .col-12
        .checkbox-container
          = form.check_box :listing_location_required
          = form.label :listing_location_required, t(".this_field_is_required")

    = render :partial => "admin/custom_fields/form/buttons", :locals => { :form => form }

app/views/admin/custom_fields/edit_price.haml
- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t(".edit_price_field")

- content_for :extra_javascript do
  :javascript
    initialize_admin_edit_price($("#edit_community"), "community[price_filter_min]", "community[price_filter_max]", "#{I18n.locale}");

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section
  = form_for @community, :as => :community, :url => update_price_admin_custom_fields_path, :method => :put do |form|

    - min = MoneyUtil.to_units(MoneyUtil.to_money(@current_community.price_filter_min, @current_community.default_currency)) || 0
    - max = MoneyUtil.to_units(MoneyUtil.to_money(@current_community.price_filter_max, @current_community.default_currency)) || 100000

    .row
      .col-12
        .checkbox-container
          = form.check_box :show_price_filter
          = form.label :show_price_filter, t(".show_price_filter_homepage")

    .row
      .col-3
        = form.label "community[price_filter_min]", t(".price_min")
        = text_field_tag "community[price_filter_min]", min, :class => "required number-no-decimals"
      .col-3
        = form.label "community[price_filter_max]", t(".price_max")
        = text_field_tag "community[price_filter_max]", max, :class => "required number-no-decimals"

    = render :partial => "admin/custom_fields/form/buttons", :locals => { :form => form }

app/views/admin/custom_fields/index.haml
- content_for :javascript do
  ST.createCustomFieldOrder(".custom-field-list-row");

- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t(".listing_fields")

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section

  .row
    .col-12
    %h3
      = t(".listing_fields")

    = render :partial => "layouts/info_text", :locals => { :text => t(".listing_fields_help")}

    - show_custom_fields = !@custom_fields.empty?

  #custom-fields-list
    .row.visible-tablet
      .col-5.custom-fields-list-title
        = t(".field_title")
      .col-5.custom-fields-list-title
        = t(".field_type")

    .row
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_title")
        = t("listings.form.title.listing_title")
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_type")
        %div
          = t("admin.custom_fields.field_types.text")
        %div.custom-fields-details
      .col-2
        = icon_tag("edit", ["icon-fix disabled"])
        = icon_tag("cross", ["icon-fix disabled"])
        = icon_tag("directup", ["icon-fix disabled"])
        = icon_tag("directdown", ["icon-fix disabled"])

    - if show_price_filter
      / This is ugly piece of hard-coded copy-paste code.
      / In the future we'll make also the price to be a custom field
      .row.custom-field-price-row
        .col-5
          %span.custom-fields-mobile-list-title.hidden-tablet
            = t("admin.custom_fields.index.field_title")
          = t("listings.form.price.price")
        .col-5
          %span.custom-fields-mobile-list-title.hidden-tablet
            = t("admin.custom_fields.index.field_type")
          %div
            = t("listings.form.price.price")
          %div.custom-fields-details
        .col-2
          = link_to edit_price_admin_custom_fields_path, :class => "custom-fields-action-edit" do
            = icon_tag("edit", ["icon-fix"])
          = icon_tag("cross", ["icon-fix disabled"])
          = icon_tag("directup", ["icon-fix disabled"])
          = icon_tag("directdown", ["icon-fix disabled"])

    .row
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_title")
        = t("listings.form.description.detailed_description")
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_type")
        %div
          = t("admin.custom_fields.field_types.text")
        %div.custom-fields-details
      .col-2
        = icon_tag("edit", ["icon-fix disabled"])
        = icon_tag("cross", ["icon-fix disabled"])
        = icon_tag("directup", ["icon-fix disabled"])
        = icon_tag("directdown", ["icon-fix disabled"])

    - if show_custom_fields
      = render :partial => "listed_custom_field", :collection => @custom_fields.sort, :as => :custom_field

    - unless @current_community.hide_expiration_date
      .row
        .col-5
          %span.custom-fields-mobile-list-title.hidden-tablet
            = t("admin.custom_fields.index.field_title")
          = t("listings.form.valid_until.valid_until")
        .col-5
          %span.custom-fields-mobile-list-title.hidden-tablet
            = t("admin.custom_fields.index.field_type")
          %div
            = t("admin.custom_fields.field_types.date")
          %div.custom-fields-details
        .col-2
          = icon_tag("edit", ["icon-fix disabled"])
          = icon_tag("cross", ["icon-fix disabled"])
          = icon_tag("directup", ["icon-fix disabled"])
          = icon_tag("directdown", ["icon-fix disabled"])

    .row
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_title")
        = t("listings.form.location.location")
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_type")
        %div
          = t("listings.form.location.location")
        %div.custom-fields-details
      .col-2
        = link_to edit_location_admin_custom_fields_path, :class => "custom-fields-action-edit" do
          = icon_tag("edit", ["icon-fix"])
        = icon_tag("cross", ["icon-fix disabled"])
        = icon_tag("directup", ["icon-fix disabled"])
        = icon_tag("directdown", ["icon-fix disabled"])

    .row
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_title")
        = t("listings.form.images.image")
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_type")
        %div
          = t("listings.form.images.image")
        %div.custom-fields-details
      .col-2
        = icon_tag("edit", ["icon-fix disabled"])
        = icon_tag("cross", ["icon-fix disabled"])
        = icon_tag("directup", ["icon-fix disabled"])
        = icon_tag("directdown", ["icon-fix disabled"])

    #custom-field-ajax-status
      .ajax-notification.ajax-notice.custom-field-ajax-status-message#custom-field-ajax-saving
        .ajax-icon{:class => icon_class("loading")}
        .ajax-text
          = t(".saving_order")
      .ajax-notification.ajax-success.custom-field-ajax-status-message#custom-field-ajax-success
        .ajax-icon{:class => icon_class("check")}
        .ajax-text
          = t(".save_order_successful")
      .ajax-notification.ajax-error.custom-field-ajax-status-message#custom-field-ajax-error
        = t(".save_order_error")

  .row.new-custom-field-type-form
    = form_tag new_admin_custom_field_path, :method => :get do |form|
      .new-custom-field-type-form-column
        = t(".add_new_field")
      .new-custom-field-type-form-column
        = select_tag :field_type, options_for_select(custom_field_dropdown_options(CustomField::VALID_TYPES)), :onChange => "form.submit();"