config/routes.rb
Kassi::Application.routes.draw do
  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  match "/robots.txt" => RobotsGenerator

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  match "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get '/webhooks/braintree' => 'braintree_webhooks#challenge'
  post '/webhooks/braintree' => 'braintree_webhooks#hooks'
  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook

  post '/bounces' => 'amazon_bounces#notification'

  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  match "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :admin do
    match '' => "communities#getting_started"
  end

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    get "/check_email_availability" => "marketplaces#check_email_availability"
  end

  REMOVED_LOCALES = Rails.application.config.REMOVED_LOCALES.to_a

  locale_matcher = Regexp.new(Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(REMOVED_LOCALES).join("|"))

  match '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  match '/' => 'homepage#index', as: :homepage_without_locale
  root :to => 'homepage#index'

  match '/500' => 'errors#server_error'
  match '/404' => 'errors#not_found', :as => :error_not_found
  match '/410' => 'errors#gone', as: :error_gone
  match '/community_not_found' => 'errors#community_not_found', as: :community_not_found

  resources :communities, only: [:new, :create]

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    match '/mercury_update' => "mercury_update#update", :as => :mercury_update, :method => :put

    match "/transactions/op_status/:process_token" => "transactions#op_status", :as => :transaction_op_status

    match "/transactions/new" => "transactions#new", as: :new_transaction

    match "/listings/:listing_id/preauthorize" => "preauthorize_transactions#preauthorize", :as => :preauthorize_payment
    match "/listings/:listing_id/preauthorized" => "preauthorize_transactions#preauthorized", :as => :preauthorized_payment
    match "/listings/:listing_id/book" => "preauthorize_transactions#book", :as => :book
    match "/listings/:listing_id/booked" => "preauthorize_transactions#booked", :as => :booked
    match "/listings/:listing_id/initiate" => "preauthorize_transactions#initiate", :as => :initiate_order
    match "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    match "/listings/:listing_id/post_pay" => "post_pay_transactions#new", :as => :post_pay_listing
    match "/listings/:listing_id/create_transaction" => "post_pay_transactions#create", :as => :create_transaction, :method => :post

    match "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    match "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    match "/listings/new/:type/:category" => "listings#new", :as => :new_request_category
    match "/listings/new/:type" => "listings#new", :as => :new_request
    match "/logout" => "sessions#destroy", :as => :logout, :method => :delete
    match "/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
    match "/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
    match "/login" => "sessions#new", :as => :login
    match "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    match "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    match '/:person_id/settings/payments/braintree/new' => 'braintree_accounts#new', :as => :new_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/show' => 'braintree_accounts#show', :as => :show_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/create' => 'braintree_accounts#create', :as => :create_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/add_braintree_customer' => 'braintree_accounts#add_braintree_customer', :as => :add_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/update_braintree_customer' => 'braintree_accounts#update_braintree_customer', :as => :update_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/create_braintree_customer' => 'braintree_accounts#create_braintree_customer', :as => :create_braintree_settings_customer
    match '/:person_id/settings/payments/paypal_account/new' => 'paypal_accounts#new', :as => :new_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/show' => 'paypal_accounts#show', :as => :show_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/create' => 'paypal_accounts#create', :as => :create_paypal_account_settings_payment
    get '/auth_stripe' =>"transactions#auth_stripe"
    post "/listing_calculation" => "listings#listing_calculation"

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do

      resources :communities do
        member do
          get :getting_started, to: 'communities#getting_started'
          get :edit_details, to: 'community_customizations#edit_details'
          put :update_details, to: 'community_customizations#update_details'
          get :edit_look_and_feel
          put :edit_look_and_feel, to: 'communities#update_look_and_feel'
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :settings
          get :payment_gateways
          put :payment_gateways, to: 'communities#update_payment_gateway'
          post :payment_gateways, to: 'communities#create_payment_gateway'
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          get :menu_links
          put :menu_links, to: 'communities#update_menu_links'
          put :update_settings
          delete :delete_marketplace
        end
        resources :transactions, controller: :community_transactions, only: :index
        resources :emails
        resources :community_memberships do
          member do
            put :ban
            put :verify_user
          end
          collection do
            post :promote_admin
            post :posting_allowed
          end
        end
        resource :paypal_preferences, only: :index do
          member do
            get :index
            post :preferences_update
            get :account_create
            get :permissions_verified
          end
        end
      end
      resources :custom_fields do
        collection do
          get :add_option
          get :edit_price
          get :edit_location
          post :order
          put :update_price
          put :update_location
        end
      end
      resources :categories do
        member do
          get :remove
          delete :destroy_and_move
        end
        collection do
          post :order
        end
      end
      resources :listing_shapes do
        collection do
          post :order
        end
        member do
          get :close_listings
        end
      end
    end

    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :community_memberships, :as => :tribe_memberships do
      collection do
        get :access_denied
      end
    end
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :new_form_content
        get :edit_form_content
        get :more_listings
        get :browse
        get :locations_json
        get :verification_required
      end
      resources :comments
      resources :listing_images do
        collection do
          post :add_from_file
          put :add_from_url
        end
      end
    end

    resources :listing_images do
      member do
        get :image_status
      end
      collection do
        post :add_from_file
        put :add_from_url
      end
    end

    resources :infos do
      collection do
        get :about
        get :terms
        get :privacy
        get :news
        get :trust_and_safety
        get :faq
        get :claim
        get :contact
      end
    end
    resource :terms do
      member do
        post :accept
      end
    end
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end
    resources :consent
    resource :sms do
      get :message_arrived
    end

    devise_for :people, :controllers => { :confirmations => "confirmations", :registrations => "people", :omniauth_callbacks => "sessions"}, :path_names => { :sign_in => 'login'}
    devise_scope :person do
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      match "/people/password/edit" => "devise/passwords#edit"
      post "/people/password" => "devise/passwords#create"
      put "/people/password" => "devise/passwords#update"

app/models/paypal_account.rb
# == Schema Information
#
# Table name: paypal_accounts
#
#  id           :integer          not null, primary key
#  person_id    :string(255)
#  community_id :integer
#  email        :string(255)
#  payer_id     :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  active       :boolean          default(FALSE)
#
# Indexes
#
#  index_paypal_accounts_on_community_id  (community_id)
#  index_paypal_accounts_on_payer_id      (payer_id)
#  index_paypal_accounts_on_person_id     (person_id)
#

class PaypalAccount < ActiveRecord::Base
  attr_accessible :email, :payer_id, :person_id, :community_id, :active

  belongs_to :person
  belongs_to :community
  has_one :order_permission, dependent: :destroy
  has_one :billing_agreement, dependent: :destroy
end

app/views/paypal_accounts/_ask_paypal_billing_agreement.haml
.row.paypal-connected-email-row
  %h3.paypal-account-connected
    =t("paypal_accounts.paypal_account_email_connected").html_safe
  .paypal-connected-email.paypal-account-connected
    = t("paypal_accounts.connected_account", :email => paypal_account_email)
  .paypal-connected-change
    = link_to t("paypal_accounts.change_account"), change_url

- if commission_type != :none
  .row
    = form.label :paypal_email, t("paypal_accounts.new.paypal_account_billing_agreement")

  .row
    - paypal_info_link = "<a id='paypal_fee_info_link' href='#'>#{t("paypal_accounts.new.paypal_info_link_text")}</a>"
    - if commission_type == :both
      = render :partial => "layouts/info_text", :locals => {text: t("paypal_accounts.new.paypal_account_billing_agreement_info_both",
      commission_from_seller: commission_from_seller,
      minimum_commission: humanized_money_with_symbol(minimum_commission),
      paypal_info_link: paypal_info_link).html_safe }
    - elsif commission_type == :relative
      = render :partial => "layouts/info_text", :locals => {text: t("paypal_accounts.new.paypal_account_billing_agreement_info_relative",
      commission_from_seller: commission_from_seller,
      paypal_info_link: paypal_info_link).html_safe }
    - elsif commission_type == :fixed
      = render :partial => "layouts/info_text", :locals => {text: t("paypal_accounts.new.paypal_account_billing_agreement_info_fixed",
      minimum_commission: humanized_money_with_symbol(minimum_commission),
      paypal_info_link: paypal_info_link).html_safe }

  .row.send-button-wrapper
    = form.button t("paypal_accounts.new.billing_agreement"), :class => "send_button"

  = render layout: "layouts/lightbox", locals: { id: "paypal_fee_info_content"} do
    %h2= t("common.paypal_fee_info.title")
    - text_with_line_breaks_html_safe do
      - link_to_paypal = link_to(t("common.paypal_fee_info.link_to_paypal_text"), paypal_fees_url)
      = t("common.paypal_fee_info.body_text", link_to_paypal: link_to_paypal).html_safe

  - content_for :extra_javascript do
    :javascript
      $('#paypal_fee_info_link').click(function() { $('#paypal_fee_info_content').lightbox_me({centered: true, zIndex: 1000000}); });

app/views/paypal_accounts/_ask_paypal_permissions.haml
.row
  = form.label :paypal_email, title
.row
  - create_link = link_to(I18n.t("paypal_accounts.new.create_paypal_account"), create_url, target: "_blank")
  - upgrade_link = link_to(I18n.t("paypal_accounts.new.upgrade_paypal_account"), upgrade_url, target: "_blank")
  - text = t("paypal_accounts.new.paypal_account_email_info_text", {create_paypal_account: create_link, upgrade_paypal_account: upgrade_link, currency: "<strong>#{currency}</strong>"}).html_safe
  = render :partial => "layouts/info_text", :locals => {text: text}

.row.send-button-wrapper
  = form.button t("paypal_accounts.new.connect_paypal_account"), :class => "send_button"

app/views/paypal_accounts/new.haml
- content_for :javascript do
  ST.initializePayPalAccountForm("paypal_account_form");

= render :partial => "layouts/left_hand_navigation", :locals => { :links => left_hand_navigation_links }

.left-navi-section.settings-section.payment-settings

  %h2= t("paypal_accounts.payout_info_title")

  .row
    = t("paypal_accounts.new.payout_info_you_need_to_connect")

  - if community_ready_for_payments
    .row
      = t("paypal_accounts.new.payout_info_text").html_safe

    %br/

    - if paypal_account_state == :verified
      = form_for paypal_account_form, :url => billing_agreement_action, method: "get", :html => { :id => "paypal_account_form"} do |form|
        = render :partial => "ask_paypal_billing_agreement", locals: {paypal_account_email: paypal_account_email, form: form, change_url: change_url, commission_type: commission_type, commission_from_seller: commission_from_seller, minimum_commission: minimum_commission, paypal_fees_url: paypal_fees_url}
    - else
      = form_for paypal_account_form, :url => order_permission_action, method: "get", :html => { :id => "paypal_account_form"} do |form|
        - title = t("paypal_accounts.new.paypal_account_email")
        = render :partial => "ask_paypal_permissions", locals: {form: form, title: title, currency: currency, create_url: create_url, upgrade_url: upgrade_url}

        %br/
        .row
          = form.label :paypal_email, t("paypal_accounts.new.paypal_account_billing_agreement", commission: commission_from_seller), :class => "input disabled"

app/views/paypal_accounts/show.haml
= render :partial => "layouts/left_hand_navigation", :locals => { :links => left_hand_navigation_links }

.left-navi-section.settings-section.payment-settings

  %h2= t("paypal_accounts.payout_info_title")

  - if community_ready_for_payments
    .row
      = t("paypal_accounts.new.payout_info_text").html_safe

    %br/

    .row.paypal-connected-email-row
      %h3.paypal-account-connected
        = t("paypal_accounts.paypal_account_email_connected").html_safe
      .paypal-connected-email.paypal-account-connected
        = t("paypal_accounts.connected_account", :email => paypal_account_email)
      .paypal-connected-change
        = link_to t("paypal_accounts.change_account"), change_url

    - if paypal_account_state == :verified
      .row.paypal-billing-agreement-row
        %h3.paypal-billing-agreement-made
          = t("paypal_accounts.paypal_billing_agreement_made").html_safe
        .paypal-billing-agreement-made.paypal-ready-to-accept-payments
          = t("paypal_accounts.you_are_ready_to_accept_payments").html_safe