config/routes.rb
    match '/:person_id/settings/payments/braintree/update_braintree_customer' => 'braintree_accounts#update_braintree_customer', :as => :update_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/create_braintree_customer' => 'braintree_accounts#create_braintree_customer', :as => :create_braintree_settings_customer
    match '/:person_id/settings/payments/paypal_account/new' => 'paypal_accounts#new', :as => :new_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/show' => 'paypal_accounts#show', :as => :show_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/create' => 'paypal_accounts#create', :as => :create_paypal_account_settings_payment
    get '/auth_stripe' =>"transactions#auth_stripe"
    post "/listing_calculation" => "listings#listing_calculation"

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do

      resources :communities do
        member do
          get :getting_started, to: 'communities#getting_started'
          get :edit_details, to: 'community_customizations#edit_details'
          put :update_details, to: 'community_customizations#update_details'
          get :edit_look_and_feel
          put :edit_look_and_feel, to: 'communities#update_look_and_feel'
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :settings
          get :payment_gateways
          put :payment_gateways, to: 'communities#update_payment_gateway'
          post :payment_gateways, to: 'communities#create_payment_gateway'
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          get :menu_links
          put :menu_links, to: 'communities#update_menu_links'
          put :update_settings
          delete :delete_marketplace
        end
        resources :transactions, controller: :community_transactions, only: :index
        resources :emails
        resources :community_memberships do
          member do
            put :ban
            put :verify_user
          end
          collection do
            post :promote_admin
            post :posting_allowed
          end
        end
        resource :paypal_preferences, only: :index do
          member do
            get :index
            post :preferences_update
            get :account_create
            get :permissions_verified
          end
        end
      end
      resources :custom_fields do
        collection do
          get :add_option
          get :edit_price
          get :edit_location
          post :order
          put :update_price
          put :update_location
        end
      end
      resources :categories do
        member do
          get :remove
          delete :destroy_and_move
        end
        collection do
          post :order
        end
      end
      resources :listing_shapes do
        collection do
          post :order
        end
        member do
          get :close_listings
        end
      end
    end

    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :community_memberships, :as => :tribe_memberships do
      collection do
        get :access_denied
      end
    end
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :new_form_content
        get :edit_form_content
        get :more_listings
        get :browse
        get :locations_json
        get :verification_required
      end
      resources :comments
      resources :listing_images do
        collection do
          post :add_from_file
          put :add_from_url
        end
      end
    end

    resources :listing_images do
      member do
        get :image_status
      end
      collection do
        post :add_from_file
        put :add_from_url
      end
    end

    resources :infos do
      collection do
        get :about
        get :terms
        get :privacy
        get :news
        get :trust_and_safety
        get :faq
        get :claim
        get :contact
      end
    end
    resource :terms do
      member do
        post :accept
      end
    end
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end
    resources :consent
    resource :sms do
      get :message_arrived
    end

    devise_for :people, :controllers => { :confirmations => "confirmations", :registrations => "people", :omniauth_callbacks => "sessions"}, :path_names => { :sign_in => 'login'}
    devise_scope :person do
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      match "/people/password/edit" => "devise/passwords#edit"
      post "/people/password" => "devise/passwords#create"
      put "/people/password" => "devise/passwords#update"
      match "/people/sign_up" => redirect("/%{locale}/login")

      match "/signup" => "people#new", :as => :sign_up
      match '/people/auth/:provider/setup' => 'sessions#facebook_setup' #needed for devise setup phase hook to work

      resources :people, :path => "", :only => :show, :constraints => { :id => /[_a-z0-9]+/ }

      resources :people, :constraints => { :id => /[_a-z0-9]+/ } do
        collection do
          get :check_username_availability
          get :check_email_availability
          get :check_email_availability_and_validity
          get :check_invitation_code
          get :not_member
          get :cancel
          get :create_facebook_based
          get :verify_vat_number
        end
      end

      resources :people, :path => "" do
        member do
          put :activate
          put :deactivate
        end
        resources :listings do
          member do
            put :close
            put :move_to_top
            put :show_in_updates_email
          end
        end
        resources :person_messages

        resource :inbox, :only => [:show]

        resources :messages, :controller => :conversations do
          collection do
            get :received, to: 'inboxes#show'
          end
          member do
            get :accept, to: 'accept_conversations#accept'
            get :reject, to: 'accept_conversations#reject'
            put :acceptance, to: 'accept_conversations#acceptance'
            get :confirm, to: 'confirm_conversations#confirm'
            get :cancel, to: 'confirm_conversations#cancel'
            put :confirmation, to: 'confirm_conversations#confirmation' #TODO these should be under transaction
            get :accept_preauthorized, to: 'accept_preauthorized_conversations#accept'
            get :reject_preauthorized, to: 'accept_preauthorized_conversations#reject'
            put :acceptance_preauthorized, to: 'accept_preauthorized_conversations#accepted_or_rejected'
          end
          resources :messages
          resources :feedbacks, :controller => :testimonials do
            collection do
              put :skip
            end
          end
          resources :payments do
            member do
              get :done
            end
          end
          resources :braintree_payments
        end
        resources :braintree_payments do
          get :add_braintree_customer
          post :create_braintree_customer
        end
        resource :paypal_account, only: [:new, :show] do
          member do
            get :ask_order_permission
            get :ask_billing_agreement
            get :permissions_verified
            get :paypal_connect
            get :billing_agreement_success
            get :billing_agreement_cancel
          end
        end
        resources :transactions, only: [:show, :new, :create] do
          member do
            post :notification_status
            post :pay_stripe_amount
          end
        end
        resource :checkout_account, only: [:new, :show, :create]
        resource :settings do
          member do
            get :account
            get :notifications
            get :payments
            get :unsubscribe
            get :insurance
            get :id_verification
            post :update_person_details
            get :strip_credit_detail
            post :create_credit_detail
            get :strip_update_detail
            post :update_credit_detail
            get :stripe_connect
            get :sms_notification
            post :get_currency
            post :save_stripe_details
            post :update_stripe_details
            post :select_stripe_account
            post :delete_stripe_account
          end
        end
        resources :testimonials
        resources :emails do
          member do
            post :send_confirmation
          end
        end
        resources :followers
        resources :followed_people
      end # people

    end # devise scope person

    match "/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation

    get '/:person_id/settings/profile', to: redirect("/%{person_id}/settings") #needed to keep old links working

  end # scope locale

  id_to_username = Proc.new do |params, req|
    username = Person.find(params[:person_id]).try(:username)
    locale = params[:locale] + "/" if params[:locale]
    if username
      "/#{locale}#{username}#{params[:path]}"
    else
      "/404"
    end
  end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  listing_id      :integer
#  created_at      :datetime
#  updated_at      :datetime
#  last_message_at :datetime
#  community_id    :integer
#
# Indexes
#
#  index_conversations_on_community_id     (community_id)
#  index_conversations_on_last_message_at  (last_message_at)
#  index_conversations_on_listing_id       (listing_id)
#

class Conversation < ActiveRecord::Base

  has_many :messages, :dependent => :destroy

  has_many :participations, :dependent => :destroy
  has_many :participants, :through => :participations, :source => :person
  belongs_to :listing
  has_one :transaction
  belongs_to :community

  scope :for_person, -> (person){
    joins(:participations)
    .where( { participations: { person_id: person }} )
  }

  # Creates a new message to the conversation
  def message_attributes=(attributes)
    if attributes[:content].present? || attributes[:action].present?
      messages.build(attributes)
    end
  end

  # Sets the participants of the conversation
  def conversation_participants=(conversation_participants)
    conversation_participants.each do |participant, is_sender|
      last_at = is_sender.eql?("true") ? "last_sent_at" : "last_received_at"
      participations.build(:person_id => participant,
                           :is_read => is_sender,
                           :is_starter => is_sender,
                           last_at.to_sym => DateTime.now)
    end
  end

  def participation_for(person)
    participations.find { |participation| participation.person_id == person.id }
  end

  def build_starter_participation(person)
    participations.build(
      person: person,
      is_read: true,
      is_starter: true,
      last_sent_at: DateTime.now
    )
  end

  def build_participation(person)
    participations.build(
      person: person,
      is_read: false,
      is_starter: false,
      last_received_at: DateTime.now
    )
  end

  # Returns last received or sent message
  def last_message
    return messages.last
  end

  def first_message
    return messages.first
  end

  def other_party(person)
    participants.reject { |p| p.id == person.id }.first
  end

  def read_by?(person)
    participation_for(person).is_read
  end

  # Send email notification to message receivers and returns the receivers
  #
  # TODO This should be removed. It's not model's resp to send emails.
  def send_email_to_participants(community)
    recipients(messages.last.sender).each do |recipient|
      if recipient.should_receive?("email_about_new_messages")
        PersonMailer.new_message_notification(messages.last, community).deliver
      end
    end
  end

  # Returns all the participants except the message sender
  def recipients(sender)
    participants.reject { |p| p.id == sender.id }
  end

  def starter
    Maybe(participations.find { |p| p.is_starter? }).person.or_else(nil)
  end

  def participant?(user)
    participants.include? user
  end

  def with_type(&block)
    block.call(:conversation)
  end

  def with(expected_type, &block)
    with_type do |own_type|
      if own_type == expected_type
        block.call
      end
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  include MoneyRails::ActionViewExtension

  MessageForm = Form::Message

  before_filter do |controller|
    controller.ensure_logged_in t("layouts.notifications.you_must_log_in_to_view_your_inbox")
  end

  def show
    conversation_id = params[:id]

    conversation = MarketplaceService::Conversation::Query.conversation_for_person(
      conversation_id,
      @current_user.id,
      @current_community.id)

    if conversation.blank?
      flash[:error] = t("layouts.notifications.you_are_not_authorized_to_view_this_content")
      return redirect_to root
    end

    transaction = Transaction.find_by_conversation_id(conversation[:id])

    if transaction.present?
      # We do not want to use this controller to show conversations with transactions
      # as the transaction controller shows not only the messages, but also the actions
      # so redirect there.
      redirect_to person_transaction_url(@current_user, {:id => transaction.id}) and return
    end

    message_form = MessageForm.new({sender_id: @current_user.id, conversation_id: conversation_id})

    conversation[:other_person] = person_entity_with_url(conversation[:other_person])

    messages = TransactionViewUtils.conversation_messages(conversation[:messages], @current_community.name_display_type)

    MarketplaceService::Conversation::Command.mark_as_read(conversation[:id], @current_user.id)

    render locals: {
      messages: messages.reverse,
      conversation_data: conversation,
      message_form: message_form,
      message_form_action: person_message_messages_path(@current_user, :message_id => conversation[:id])
    }
  end

  def person_entity_with_url(person_entity)
    person_entity.merge({
                          url: person_path(id: person_entity[:username]),
                          display_name: PersonViewUtils.person_entity_display_name(person_entity, @current_community.name_display_type)
                        })
  end
end

app/views/conversations/_conversation_header.haml
- content_for :title_header do
  %h1
    = link_to person_inbox_path(@current_user), :class => "transaction_head" do
      = t("layouts.no_tribe.inbox")
    |
    %span{:id => "inbox-conversation"}
      = t("conversations.show.conversation_with", person: link_to_unless(other_party[:is_deleted], other_party[:display_name], other_party[:url], :class => "transaction_head")).html_safe

app/views/conversations/_conversation_with.haml
- if conversation.listing
  - if conversation.status.eql?("free")
    = t("conversations.show.conversation_about_listing", :person => link_to(other_party.name(@current_community), other_party), :listing => link_to(conversation.listing.title, conversation.listing)).html_safe
  - else
    - if current_user?(conversation.messages.first.sender)
      = t("conversations.show.message_sent_to")
      = link_to other_party.name(@current_community), other_party
    - else
      = t("conversations.show.message_sent_by")
      = link_to(other_party.name(@current_community), other_party)
    = t("conversations.show.in_response_to_listing")
    = link_to(conversation.listing.title, conversation.listing)
- else
  = t("conversations.show.conversation_with_user", :person => link_to(other_party.name(@current_community), other_party)).html_safe

app/views/conversations/_details.haml
- Maybe(listing).map do |listing|
  %p
    - price = Maybe(listing).price.or_else(nil)
    - sum = Maybe(transaction).payment.total_sum.or_else(nil)

    - Maybe(transaction).booking.each do |booking|
      %ul.no-bullets
        %li
          %div
            = l booking.start_on, format: :long_with_abbr_day_name
            = "-"
            = l booking.end_on, format: :long_with_abbr_day_name
            = "(#{pluralize(booking.duration, t(".day"), t(".days"))})"

        %li
          %div
            = t(".price_per_day", price: humanized_money_with_symbol(listing.price))

    - if sum
      %p.message-sum
        = t("conversations.show.sum", sum: humanized_money_with_symbol(sum))
    - elsif price
      %p.message-price
        = t("conversations.show.price", price: humanized_money_with_symbol(listing.price))

        - if listing.quantity.present?
          = "/ #{listing.quantity}"

        - elsif listing.unit_type.present?
          = "/ #{ListingViewUtils.translate_unit(listing.unit_type, listing.unit_tr_key)}"

        - if @current_community.vat
          %span.message-price-vat
            = t("conversations.show.price_excludes_vat")

app/views/conversations/_inbox_spacer.haml
.inbox_spacer

app/views/conversations/_message.haml
- avatar_side = message_or_action[:sender][:id] == @current_user.id ? "left" : "right"

.row.message-row
  .col-12.message-container
    %div{class: "message-avatar-#{avatar_side}"}
      = image_tag(message_or_action[:sender][:avatar], :class => "message-avatar-image")
    %div{class: "message-content-container-#{avatar_side}"}
      %div{class: "message-time-ago-#{avatar_side}"}
        = link_to_unless message_or_action[:sender][:is_deleted], message_or_action[:sender][:display_name], person_path(id: message_or_action[:sender][:username])
        = time_ago(message_or_action[:created_at])

      %div{class: "message-bubble-arrow-to-#{avatar_side} message-type-#{message_or_action[:type]} message-mood-#{message_or_action[:mood]}"}
        %div
          - text_with_line_breaks do
            = message_or_action[:content]

app/views/conversations/_messages_and_form.haml
- if role == :participant
  - content_for :javascript do
    initialize_reply_form('#{I18n.locale}');

  #reply_form.message-avatar-padding.message-reply-form
    = form_for message_form, :url => message_form_action do |f|
      = f.label :content, t("conversations.show.write_a_reply")
      = f.text_area :content, :class => "reply_form_text_area"
      = f.hidden_field :conversation_id
      = f.hidden_field :sender_id
      = f.button t("conversations.show.send_reply"), :class =>"send_reply_msg"

#messages
  = render :partial => "conversations/message", :collection => messages, as: :message_or_action

app/views/conversations/show.haml
= render :partial => "conversations/conversation_header", locals: {other_party: conversation_data[:other_person]}

.centered-section-wide
  = render :partial => "conversations/messages_and_form", locals: {role: :participant, message_form: message_form, message_form_action: message_form_action, messages: messages}