config/routes.rb
Kassi::Application.routes.draw do
  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  match "/robots.txt" => RobotsGenerator

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  match "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get '/webhooks/braintree' => 'braintree_webhooks#challenge'
  post '/webhooks/braintree' => 'braintree_webhooks#hooks'
  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook

  post '/bounces' => 'amazon_bounces#notification'

  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  match "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :admin do
    match '' => "communities#getting_started"
  end

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    get "/check_email_availability" => "marketplaces#check_email_availability"
  end

  REMOVED_LOCALES = Rails.application.config.REMOVED_LOCALES.to_a

  locale_matcher = Regexp.new(Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(REMOVED_LOCALES).join("|"))

  match '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  match '/' => 'homepage#index', as: :homepage_without_locale
  root :to => 'homepage#index'

  match '/500' => 'errors#server_error'
  match '/404' => 'errors#not_found', :as => :error_not_found
  match '/410' => 'errors#gone', as: :error_gone
  match '/community_not_found' => 'errors#community_not_found', as: :community_not_found

  resources :communities, only: [:new, :create]

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    match '/mercury_update' => "mercury_update#update", :as => :mercury_update, :method => :put

    match "/transactions/op_status/:process_token" => "transactions#op_status", :as => :transaction_op_status

    match "/transactions/new" => "transactions#new", as: :new_transaction

    match "/listings/:listing_id/preauthorize" => "preauthorize_transactions#preauthorize", :as => :preauthorize_payment
    match "/listings/:listing_id/preauthorized" => "preauthorize_transactions#preauthorized", :as => :preauthorized_payment
    match "/listings/:listing_id/book" => "preauthorize_transactions#book", :as => :book
    match "/listings/:listing_id/booked" => "preauthorize_transactions#booked", :as => :booked
    match "/listings/:listing_id/initiate" => "preauthorize_transactions#initiate", :as => :initiate_order
    match "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    match "/listings/:listing_id/post_pay" => "post_pay_transactions#new", :as => :post_pay_listing
    match "/listings/:listing_id/create_transaction" => "post_pay_transactions#create", :as => :create_transaction, :method => :post

    match "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    match "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    match "/listings/new/:type/:category" => "listings#new", :as => :new_request_category
    match "/listings/new/:type" => "listings#new", :as => :new_request
    match "/logout" => "sessions#destroy", :as => :logout, :method => :delete
    match "/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
    match "/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
    match "/login" => "sessions#new", :as => :login
    match "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    match "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    match '/:person_id/settings/payments/braintree/new' => 'braintree_accounts#new', :as => :new_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/show' => 'braintree_accounts#show', :as => :show_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/create' => 'braintree_accounts#create', :as => :create_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/add_braintree_customer' => 'braintree_accounts#add_braintree_customer', :as => :add_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/update_braintree_customer' => 'braintree_accounts#update_braintree_customer', :as => :update_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/create_braintree_customer' => 'braintree_accounts#create_braintree_customer', :as => :create_braintree_settings_customer
    match '/:person_id/settings/payments/paypal_account/new' => 'paypal_accounts#new', :as => :new_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/show' => 'paypal_accounts#show', :as => :show_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/create' => 'paypal_accounts#create', :as => :create_paypal_account_settings_payment
    get '/auth_stripe' =>"transactions#auth_stripe"
    post "/listing_calculation" => "listings#listing_calculation"

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do

      resources :communities do
        member do
          get :getting_started, to: 'communities#getting_started'
          get :edit_details, to: 'community_customizations#edit_details'
          put :update_details, to: 'community_customizations#update_details'
          get :edit_look_and_feel
          put :edit_look_and_feel, to: 'communities#update_look_and_feel'
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :settings
          get :payment_gateways
          put :payment_gateways, to: 'communities#update_payment_gateway'
          post :payment_gateways, to: 'communities#create_payment_gateway'
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          get :menu_links
          put :menu_links, to: 'communities#update_menu_links'
          put :update_settings
          delete :delete_marketplace
        end
        resources :transactions, controller: :community_transactions, only: :index
        resources :emails
        resources :community_memberships do
          member do
            put :ban
            put :verify_user
          end
          collection do
            post :promote_admin
            post :posting_allowed
          end
        end
        resource :paypal_preferences, only: :index do
          member do
            get :index
            post :preferences_update
            get :account_create
            get :permissions_verified
          end
        end
      end
      resources :custom_fields do
        collection do
          get :add_option
          get :edit_price
          get :edit_location
          post :order
          put :update_price
          put :update_location
        end
      end
      resources :categories do
        member do
          get :remove
          delete :destroy_and_move
        end
        collection do
          post :order
        end
      end
      resources :listing_shapes do
        collection do
          post :order
        end
        member do
          get :close_listings
        end
      end
    end

    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :community_memberships, :as => :tribe_memberships do
      collection do
        get :access_denied
      end
    end
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :new_form_content
        get :edit_form_content
        get :more_listings
        get :browse
        get :locations_json
        get :verification_required
      end
      resources :comments
      resources :listing_images do
        collection do
          post :add_from_file
          put :add_from_url
        end
      end
    end

    resources :listing_images do
      member do
        get :image_status
      end
      collection do
        post :add_from_file
        put :add_from_url
      end
    end

    resources :infos do
      collection do
        get :about
        get :terms
        get :privacy
        get :news
        get :trust_and_safety
        get :faq
        get :claim
        get :contact
      end
    end
    resource :terms do
      member do
        post :accept
      end
    end
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end
    resources :consent
    resource :sms do
      get :message_arrived
    end

    devise_for :people, :controllers => { :confirmations => "confirmations", :registrations => "people", :omniauth_callbacks => "sessions"}, :path_names => { :sign_in => 'login'}
    devise_scope :person do
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      match "/people/password/edit" => "devise/passwords#edit"
      post "/people/password" => "devise/passwords#create"
      put "/people/password" => "devise/passwords#update"

app/views/transactions/_details.haml
.message-avatar-padding
  .row
    .col-12

      %h2
        = link_to_unless listing[:deleted], listing[:title], listing_path(id: listing[:id]), :class => "listing_title_head"

      - if price_break_down_locals.present?
        = render partial: "transactions/price_break_down", locals: price_break_down_locals

      - if @current_community.vat.present?
        .message-price-vat
          = t("conversations.show.price_excludes_vat")

      = render partial: "transactions/shipping_address", locals: { shipping_address: tx[:shipping_address] }

      %div{:id => "transaction_status"}
        = render :partial => "transactions/status/status", :locals => { :__transaction_model => transaction_model, role: role, is_author: is_author }

app/views/transactions/_notification_status.haml
- if is_author && transaction_model.notification_status == "pending"
  .message-avatar-padding
    .row
      .col-12
        %b
          Status:
        "The renter has sent you a booking request"
        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label.request-payment-1
              = image_tag("request.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #3399ff;"}
                Request Received
            %span.initiate-transaction-per-unit-value.request-payment-2
              = button_tag t("transactions.accept"), :class => "notification_status accept_status transaction-accept", :value => "accept", :id => params[:id], :locale => params[:locale], :person_id => params[:person_id]
              = button_tag t("transactions.decline"), :class => "notification_status transaction-decline", :value => "decline", :id => params[:id], :locale => params[:locale], :person_id => params[:person_id]
              = image_tag "small_loader.gif", :class => "card_small_loader"
- if !is_author && transaction_model.notification_status == "pending"
  .message-avatar-padding
    .row
      .col-12
        %b
          Status:
        "Your request has been sent to the owner."
        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label
              = image_tag("request.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #3399ff;"}
                Request Sent
- if is_author && transaction_model.notification_status == "accept"
  .message-avatar-padding
    .row
      .col-12
        - if listing.author.strip_account_id.nil? && listing.author_id == @current_user.id
          = t("transactions.stripe_connect_owner")
        %br
        %br
        %b
          Status:
        "Waiting for accept and payment from renter."
        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label.request-payment-1
              = image_tag("pending.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #cccc00;"}
                Pending
- elsif !is_author && transaction_model.notification_status == "accept"
  .message-avatar-padding
    .row
      .col-12
        - if @current_user.card_detail.nil?
          .initiate-transaction-totals
            - stripe_url = ( @current_user.card_detail.nil? || @current_user.card_detail.id.nil?) ? strip_credit_detail_person_settings_path(@current_user, :transaction => params[:id]) : strip_update_detail_person_settings_path(@current_user, :transaction => params[:id])
            The booking has been accepted. You need to enter your payment information
            = link_to "here", stripe_url
        - else
          - if listing.author.strip_account_id.nil? && listing.author_id != @current_user.id
            = t("transactions.stripe_connect")
          - elsif listing.author.strip_account_id.nil? && listing.author_id == @current_user.id
            = t("transactions.stripe_connect_owner")
          -else
            - if price_break_down_locals[:total_label].present?
              - price = price_break_down_locals[:total]
            -else
              - price = price_break_down_locals[:listing_price]
            - if  listing.renting_out_type?
              - convenience_fee = listing.convenience_fee(price_break_down_locals[:total], @current_community)
              - pay_url = pay_stripe_amount_person_transaction_path(:person_id => @current_user.id, :id => params[:id], :price => price, :convenience_fee => convenience_fee)
            - else
              - pay_url = pay_stripe_amount_person_transaction_path(:person_id => @current_user.id, :id => params[:id], :price => price)
            %b
              Status:
            "Owner has accepted! Confirm upon agreement."
            .payment-status
              .initiate-transaction-per-unit-wrapper.notify
                %span.initiate-transaction-per-unit-label.request-payment-1
                  = image_tag("pending.png", :class => "payment-img")
                  %span{:class =>"payment-text", :style => "color: #cccc00;"}
                    Pending
                %span.initiate-transaction-per-unit-value
                  = button_to "CONFIRM", pay_url,:class => "stripe_pay_btn", :method => :post
- elsif is_author && transaction_model.notification_status == "paid"
  .message-avatar-padding
    .row
      .col-12
        %b
          Status:
        "Success! Make your gear ready for pickup. Have fun!"
        - if price_break_down_locals[:end_on].past?
          - if transaction_model.testimonials.pluck(:author_id).include?(transaction_model.listing_author_id) || transaction_model.author_skipped_feedback
            Already Reviewed.
          - else
            .status-links.row
              .inbox-horizontally-aligned-link.col-6
                %a.status-link{:href => "/#{params[:locale]}/#{transaction_model.payer.username}/messages/#{params[:id]}/feedbacks/new"}
                  = image_tag("Leave_review_feedback.png")
              .inbox-horizontally-aligned-link.col-6
                %a.status-link.cancel{"data-method" => "put", "data-remote" => "true", :href => "/#{params[:locale]}/#{transaction_model.payer.username}/messages/#{params[:id]}/feedbacks/skip"}
                  = image_tag("Skip_review.png")

        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label.request-payment-1
              = image_tag("accepted.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #00cc66;"}
                Accepted
- elsif !is_author && transaction_model.notification_status == "paid"
  .message-avatar-padding
    .row
      .col-12
        %b
          Status:
        "Success. Have fun and be creative !"
        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label.request-payment-1
              = image_tag("accepted.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #00cc66;"}
                Accepted

        - if price_break_down_locals[:end_on].past?
          - if transaction_model.testimonials.pluck(:author_id).include?(transaction_model.starter_id) || transaction_model.starter_skipped_feedback
            Already Reviewed.
          - else
            .status-links.row
              .inbox-horizontally-aligned-link.col-6
                %a.status-link{:href => "/#{params[:locale]}/#{transaction_model.payer.username}/messages/#{params[:id]}/feedbacks/new"}
                  = image_tag("Leave_review_feedback.png")
              .inbox-horizontally-aligned-link.col-6
                %a.status-link.cancel{"data-method" => "put", "data-remote" => "true", :href => "/#{params[:locale]}/#{transaction_model.payer.username}/messages/#{params[:id]}/feedbacks/skip"}
                  = image_tag("Skip_review.png")


:css
  .status-links{
    margin-top: 12px;
  }

app/views/transactions/_price_break_down.haml
.initiate-transaction-totals
  - if booking
    .initiate-transaction-per-unit-wrapper
      %span.initiate-transaction-per-unit-label
        = t("transactions.initiate.price_per_day")
      %span.initiate-transaction-per-unit-value
        = humanized_money_with_symbol(listing_price)

    .initiate-transaction-booking-wrapper
      %span.initiate-transaction-booking-label
        = t("transactions.initiate.booked_days")
      %span.initiate-transaction-booking-value
        = l start_on, format: :long_with_abbr_day_name
        = "-"
        = l end_on, format: :long_with_abbr_day_name
        = "(#{pluralize(duration, t("listing_conversations.preauthorize.day"), t("listing_conversations.preauthorize.days"))})"

  - elsif quantity.present? && localized_unit_type.present?
    .initiate-transaction-per-unit-wrapper
      %span.initiate-transaction-per-unit-label
        = t("transactions.price_per_quantity", unit_type: localized_unit_type)
      %span.initiate-transaction-per-unit-value
        = humanized_money_with_symbol(listing_price)
    - if quantity > 1
      .initiate-transaction-quantity-wrapper
        %span.initiate-transaction-quantity-label
          = localized_selector_label || t("transactions.initiate.quantity")
        %span.initiate-transaction-quantity-value
          = quantity

  - if subtotal.present?
    .initiate-transaction-sum-wrapper
      %span.initiate-transaction-sum-label
        = t("transactions.initiate.subtotal")
      %span.initiate-transaction-sum-value
        = humanized_money_with_symbol(subtotal)

  - if params[:listing_id].present? || params[:id].present?
    .initiate-transaction-sum-wrapper
      - founded_listing = choose_listing(params[:listing_id], "listing") if params[:listing_id].present?
      - founded_listing = choose_listing(params[:id], "transaction") if params[:id].present?
      - if @current_user != founded_listing.author && founded_listing.renting_out_type?
        %span.initiate-transaction-sum-label
          = t("transactions.initiate.service_fee")
        %span.initiate-transaction-sum-value
          = humanized_money_with_symbol(founded_listing.convenience_fee(subtotal.present? ? subtotal : listing_price, @current_community))

  - if shipping_price.present?
    .initiate-transaction-shipping-price-wrapper
      %span.initiate-transaction-shipping-price-label
        = t("transactions.initiate.shipping-price")
      %span.initiate-transaction-shipping-price-value
        = humanized_money_with_symbol(shipping_price)

  - if total.present?
    .initiate-transaction-total-wrapper
      %span.initiate-transaction-total-label
        - if total_label.present?
          = total_label
        - else
          = t("transactions.total")
      %span.initiate-transaction-total-value
        - if params[:listing_id].present? || params[:id].present?
          - founded_listing = choose_listing(params[:listing_id], "listing") if params[:listing_id].present?
          - founded_listing = choose_listing(params[:id], "transaction") if params[:id].present?
          - if @current_user != founded_listing.author && founded_listing.renting_out_type?
            = humanized_money_with_symbol(founded_listing.selling_price(subtotal.present? ? subtotal : listing_price))
          - else
            = humanized_money_with_symbol(total)

app/views/transactions/_shipping_address.haml
- fields = [:name, :phone, :street1, :street2, :postal_code, :city, :state_or_province, :country]

- if shipping_address && shipping_address.slice(*fields).values.any?
  .shipping-address-container
    %h2= t("shipping_address.shipping_address")
    - fields.map do |field|
      - if shipping_address[field].present?
        - if shipping_address[field] == :name
          .shipping-address-name= shipping_address[field]
        - else
          .shipping-address-row= shipping_address[field]

app/views/transactions/new.haml
- content_for :extra_javascript do
  :javascript
    ST.transaction.initializeFreeTransactionForm('#{I18n.locale}');

- content_for :title_header do
  %h1
    = action_button_label
    = link_to(listing[:title], listing_path(listing[:id]), :class =>"new_transaction_head")

#new_message_form.centered-section
  .initiate-transaction-totals
    = t("conversations.new.help_message")
  - author_link = link_to(author[:display_name], person_path(id: author[:username]))

  .preauthorize-section
    %h2.preauthorize-details-title
      = t("listing_conversations.preauthorize.details")

    %ul.no-bullets
      %li
        %div
          = t("listing_conversations.preauthorize.by", listing: link_to("#{listing[:title]}", listing_path(listing[:id])), author: author_link).html_safe

      - m_price_break_down.each do |price_break_down|
        %li
          = render partial: "transactions/price_break_down", locals: price_break_down

  = form_tag(form_action, method: :post, id: "transaction-form") do

    = hidden_field_tag(:start_on, booking_start)
    = hidden_field_tag(:end_on, booking_end)


    .preauthorize-section
      %h2
        = t("conversations.new.send_message_to_user", person: "").html_safe
        %span{:class => "new_transaction_head"}
          = author_link
      .row
        .col-12
          = text_area_tag(:message, nil, :class => "text_area")

      - if quantity
        = hidden_field_tag(:quantity, quantity)

      .row
        .col-12
          = button_tag t("conversations.new.send_message"), :class => "send_button new_transaction"

app/views/transactions/show.haml
= render :partial => "conversations/conversation_header", locals: {other_party: conversation_other_party}

.centered-section-wide

  = render :partial => "transactions/notification_status", locals: {role: role, tx: transaction, transaction_model: transaction_model, listing: listing, is_author: is_author, price_break_down_locals: price_break_down_locals}

  = render :partial => "transactions/details", locals: {role: role, tx: transaction, transaction_model: transaction_model, listing: listing, is_author: is_author, price_break_down_locals: price_break_down_locals}

  = render :partial => "conversations/messages_and_form", locals: {role: role, message_form: message_form, message_form_action: message_form_action, messages: messages}